[package]
name = "bevy_atmosphere"
description = "A procedural sky plugin for bevy"
version = "0.4.1"
edition = "2021"
authors = ["JonahPlusPlus <33059163+JonahPlusPlus@users.noreply.github.com>"]
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/bevy_atmosphere"
homepage = "https://github.com/JonahPlusPlus/bevy_atmosphere"
repository = "https://github.com/JonahPlusPlus/bevy_atmosphere"
exclude = ["/assets/", "/examples/", "/.github/"]

[dependencies]
bevy = { version = "0.9", default-features = false, features = ["bevy_asset", "bevy_render", "bevy_pbr"] }

[dev-dependencies]
bevy_spectator = "0.1"
bevy = { version = "0.9", features = ["bevy_core_pipeline", "x11"] } # load all in case docs.rs complains

[features]
default = ["detection", "dither", "procedural"]
detection = [] # enables camera detection (disable to add skyboxes manually)
dither = [] # enables dithering (disable for banding)
procedural = [] # enables the automatic addition of `AtmospherePipelinePlugin` from `AtmospherePlugin` (disable to edit the sky texture manually)

[[example]]
name = "atmosphere"
path = "examples/atmosphere.rs"

[[example]]
name = "basic"
path = "examples/basic.rs"

[[example]]
name = "cycle"
path = "examples/cycle.rs"

[[example]]
name = "detection"
path = "examples/detection.rs"

[[example]]
name = "settings"
path = "examples/settings.rs"

[[example]]
name = "splitscreen"
path = "examples/splitscreen.rs"
