[package]
name = "bevy_atmosphere_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "1.2.1"
bevy_macro_utils = "0.9"

syn = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
